import type {
  UserProfileType,
  ScheduleBlockType,
  DailyPlanType,
  PlanItemType,
  DayOfWeekType,
} from "@ppt/shared";

/**
 * Rule-based daily plan generator.
 *
 * Phase 1: Uses simple heuristics to slot fitness activities
 * around the user's existing schedule.
 *
 * Phase 2+: Will be replaced/augmented by Gemini-powered planning.
 */
export function generateDailyPlan(
  uid: string,
  profile: UserProfileType,
  scheduleBlocks: ScheduleBlockType[],
  date: string
): DailyPlanType {
  const dayOfWeek = getDayOfWeek(date);

  // Filter blocks to today
  const todayBlocks = scheduleBlocks
    .filter((b) => b.dayOfWeek === dayOfWeek)
    .sort((a, b) => a.startTime.localeCompare(b.startTime));

  const planItems: PlanItemType[] = [];

  // Find free slots and suggest activities
  const freeSlots = findFreeSlots(todayBlocks);

  for (const slot of freeSlots) {
    const durationMinutes = minutesBetween(slot.start, slot.end);

    if (durationMinutes >= 60) {
      planItems.push(
        buildWorkoutItem(slot.start, Math.min(durationMinutes, 90), profile)
      );
    } else if (durationMinutes >= 30) {
      planItems.push({
        time: slot.start,
        duration: 30,
        activity: "Quick cardio session or stretching",
        category: "gym",
        location: "CoRec",
        notes: "Short window – keep it light",
      });
    }
  }

  // Add a morning routine suggestion if no early schedule blocks
  const hasEarlyBlock = todayBlocks.some(
    (b) => b.startTime < "09:00"
  );
  if (!hasEarlyBlock) {
    planItems.unshift({
      time: "07:00",
      duration: 30,
      activity: "Morning warm-up and stretching",
      category: "wellness",
      location: "Home / Dorm",
    });
  }

  // Sort by time
  planItems.sort((a, b) => a.time.localeCompare(b.time));

  return {
    id: date,
    uid,
    date,
    items: planItems,
    generatedAt: new Date().toISOString(),
    disclaimer:
      "This plan is generated by AI and is not medical advice. " +
      "Consult a healthcare professional before starting any fitness program.",
  };
}

// ── Helpers ─────────────────────────────────────────────────────────

interface TimeSlot {
  start: string;
  end: string;
}

function findFreeSlots(blocks: ScheduleBlockType[]): TimeSlot[] {
  const slots: TimeSlot[] = [];
  const dayStart = "08:00";
  const dayEnd = "22:00";

  let cursor = dayStart;

  for (const block of blocks) {
    if (block.startTime > cursor) {
      slots.push({ start: cursor, end: block.startTime });
    }
    if (block.endTime > cursor) {
      cursor = block.endTime;
    }
  }

  if (cursor < dayEnd) {
    slots.push({ start: cursor, end: dayEnd });
  }

  return slots;
}

function minutesBetween(start: string, end: string): number {
  const [sh, sm] = start.split(":").map(Number);
  const [eh, em] = end.split(":").map(Number);
  return (eh * 60 + em) - (sh * 60 + sm);
}

function getDayOfWeek(dateStr: string): DayOfWeekType {
  const date = new Date(dateStr + "T12:00:00Z");
  const days: DayOfWeekType[] = [
    "sunday",
    "monday",
    "tuesday",
    "wednesday",
    "thursday",
    "friday",
    "saturday",
  ];
  return days[date.getUTCDay()];
}

function buildWorkoutItem(
  time: string,
  duration: number,
  profile: UserProfileType
): PlanItemType {
  const activity = profile.workoutSplit
    ? getWorkoutForSplit(profile.workoutSplit, profile.fitnessLevel)
    : getFallbackWorkout(profile.fitnessLevel);

  return {
    time,
    duration,
    activity,
    category: "gym",
    location: "CoRec Weight Room",
    notes: profile.goals.length > 0
      ? `Goals: ${profile.goals.join(", ")}`
      : undefined,
  };
}

/** Maps workout split + fitness level to a descriptive activity string. */
function getWorkoutForSplit(split: string, fitnessLevel: string): string {
  const intensityLabel: Record<string, string> = {
    beginner: "light weight, focus on form",
    intermediate: "moderate intensity",
    advanced: "progressive overload",
    athlete: "high intensity, periodized",
  };
  const intensity = intensityLabel[fitnessLevel] ?? intensityLabel["beginner"];

  const splitWorkouts: Record<string, string> = {
    ppl: `Push / Pull / Legs – ${intensity}`,
    upper_lower: `Upper / Lower split – ${intensity}`,
    full_body: `Full body workout – ${intensity}`,
    bro_split: `Muscle group focus (bro split) – ${intensity}`,
  };

  return splitWorkouts[split] ?? `Workout session – ${intensity}`;
}

/** Fallback when no workout split is set (legacy profiles). */
function getFallbackWorkout(fitnessLevel: string): string {
  const workouts: Record<string, string> = {
    beginner: "Full body workout – bodyweight exercises",
    intermediate: "Push/Pull split – moderate intensity",
    advanced: "Compound lifts – progressive overload",
    athlete: "Sport-specific training – high intensity",
  };
  return workouts[fitnessLevel] ?? workouts["beginner"];
}
