"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IcsImportResponse = exports.IcsEvent = exports.IcsImportRequest = exports.ChatResponse = exports.ChatRequest = exports.ChatMessage = exports.ChatRole = exports.FacilityUsageItem = exports.DailyPlan = exports.PlanItem = exports.UserProfile = exports.FitnessLevel = exports.ScheduleBlock = exports.DayOfWeek = void 0;
const zod_1 = require("zod");
// ── Schedule Block ──────────────────────────────────────────────────
exports.DayOfWeek = zod_1.z.enum([
    "monday",
    "tuesday",
    "wednesday",
    "thursday",
    "friday",
    "saturday",
    "sunday",
]);
exports.ScheduleBlock = zod_1.z.object({
    id: zod_1.z.string().uuid(),
    title: zod_1.z.string().min(1).max(200),
    dayOfWeek: exports.DayOfWeek,
    /** HH:mm in 24-hour format */
    startTime: zod_1.z.string().regex(/^\d{2}:\d{2}$/),
    /** HH:mm in 24-hour format */
    endTime: zod_1.z.string().regex(/^\d{2}:\d{2}$/),
    location: zod_1.z.string().max(200).optional(),
    /** e.g. "class", "work", "gym", "meal", "other" */
    category: zod_1.z.string().max(50).default("other"),
    isRecurring: zod_1.z.boolean().default(true),
});
// ── User Profile ────────────────────────────────────────────────────
exports.FitnessLevel = zod_1.z.enum(["beginner", "intermediate", "advanced"]);
exports.UserProfile = zod_1.z.object({
    uid: zod_1.z.string(),
    displayName: zod_1.z.string().max(100),
    email: zod_1.z.string().email(),
    photoUrl: zod_1.z.string().url().optional(),
    fitnessLevel: exports.FitnessLevel.default("beginner"),
    goals: zod_1.z.array(zod_1.z.string().max(100)).max(10).default([]),
    preferredFacilities: zod_1.z.array(zod_1.z.string().max(100)).max(10).default([]),
    createdAt: zod_1.z.string().datetime(),
    updatedAt: zod_1.z.string().datetime(),
});
// ── Daily Plan ──────────────────────────────────────────────────────
exports.PlanItem = zod_1.z.object({
    time: zod_1.z.string().regex(/^\d{2}:\d{2}$/),
    duration: zod_1.z.number().int().min(5).max(480),
    activity: zod_1.z.string().max(200),
    category: zod_1.z.string().max(50),
    location: zod_1.z.string().max(200).optional(),
    notes: zod_1.z.string().max(500).optional(),
});
exports.DailyPlan = zod_1.z.object({
    id: zod_1.z.string(),
    uid: zod_1.z.string(),
    date: zod_1.z.string().regex(/^\d{4}-\d{2}-\d{2}$/),
    items: zod_1.z.array(exports.PlanItem),
    generatedAt: zod_1.z.string().datetime(),
    disclaimer: zod_1.z.string().default("This plan is generated by AI and is not medical advice. " +
        "Consult a healthcare professional before starting any fitness program."),
});
// ── Facility Usage ──────────────────────────────────────────────────
exports.FacilityUsageItem = zod_1.z.object({
    facilityName: zod_1.z.string(),
    currentCount: zod_1.z.number().int().min(0),
    maxCapacity: zod_1.z.number().int().min(0),
    lastUpdated: zod_1.z.string().datetime(),
});
// ── Chat ────────────────────────────────────────────────────────────
exports.ChatRole = zod_1.z.enum(["user", "assistant"]);
exports.ChatMessage = zod_1.z.object({
    role: exports.ChatRole,
    content: zod_1.z.string().max(5000),
    timestamp: zod_1.z.string().datetime().optional(),
});
exports.ChatRequest = zod_1.z.object({
    message: zod_1.z.string().min(1).max(2000),
    conversationHistory: zod_1.z.array(exports.ChatMessage).max(50).default([]),
});
exports.ChatResponse = zod_1.z.object({
    reply: zod_1.z.string(),
    disclaimer: zod_1.z.string().default("I'm an AI fitness assistant. My responses are not medical advice."),
});
// ── ICS Import (Phase 2 scaffolding) ────────────────────────────────
exports.IcsImportRequest = zod_1.z.object({
    icsUrl: zod_1.z.string().url(),
});
exports.IcsEvent = zod_1.z.object({
    summary: zod_1.z.string(),
    startTime: zod_1.z.string().datetime(),
    endTime: zod_1.z.string().datetime(),
    location: zod_1.z.string().optional(),
    recurrence: zod_1.z.string().optional(),
});
exports.IcsImportResponse = zod_1.z.object({
    events: zod_1.z.array(exports.IcsEvent),
    warnings: zod_1.z.array(zod_1.z.string()).default([]),
});
//# sourceMappingURL=schemas.js.map