import { z } from "zod";

// ── Schedule Block ──────────────────────────────────────────────────

export const DayOfWeek = z.enum([
  "monday",
  "tuesday",
  "wednesday",
  "thursday",
  "friday",
  "saturday",
  "sunday",
]);
export type DayOfWeek = z.infer<typeof DayOfWeek>;

export const ScheduleBlock = z.object({
  id: z.string().uuid(),
  title: z.string().min(1).max(200),
  dayOfWeek: DayOfWeek,
  /** HH:mm in 24-hour format */
  startTime: z.string().regex(/^\d{2}:\d{2}$/),
  /** HH:mm in 24-hour format */
  endTime: z.string().regex(/^\d{2}:\d{2}$/),
  location: z.string().max(200).optional(),
  /** e.g. "class", "work", "gym", "meal", "other" */
  category: z.string().max(50).default("other"),
  isRecurring: z.boolean().default(true),
});
export type ScheduleBlock = z.infer<typeof ScheduleBlock>;

// ── User Profile ────────────────────────────────────────────────────

export const FitnessLevel = z.enum(["beginner", "intermediate", "advanced", "athlete"]);
export type FitnessLevel = z.infer<typeof FitnessLevel>;

export const WorkoutSplit = z.enum(["ppl", "upper_lower", "full_body", "bro_split"]);
export type WorkoutSplit = z.infer<typeof WorkoutSplit>;

export const UserProfile = z.object({
  uid: z.string(),
  displayName: z.string().max(100),
  email: z.string().email(),
  photoUrl: z.string().url().optional(),
  fitnessLevel: FitnessLevel.default("beginner"),
  goals: z.array(z.string().max(100)).max(10).default([]),
  workoutSplit: WorkoutSplit.optional(),
  preferredFacilities: z.array(z.string().max(100)).max(10).default([]),
  createdAt: z.string().datetime(),
  updatedAt: z.string().datetime(),
});
export type UserProfile = z.infer<typeof UserProfile>;

// ── Daily Plan ──────────────────────────────────────────────────────

export const PlanItem = z.object({
  time: z.string().regex(/^\d{2}:\d{2}$/),
  duration: z.number().int().min(5).max(480),
  activity: z.string().max(200),
  category: z.string().max(50),
  location: z.string().max(200).optional(),
  notes: z.string().max(500).optional(),
});
export type PlanItem = z.infer<typeof PlanItem>;

export const DailyPlan = z.object({
  id: z.string(),
  uid: z.string(),
  date: z.string().regex(/^\d{4}-\d{2}-\d{2}$/),
  items: z.array(PlanItem),
  generatedAt: z.string().datetime(),
  disclaimer: z.string().default(
    "This plan is generated by AI and is not medical advice. " +
      "Consult a healthcare professional before starting any fitness program."
  ),
});
export type DailyPlan = z.infer<typeof DailyPlan>;

// ── Facility Usage ──────────────────────────────────────────────────

export const FacilityUsageItem = z.object({
  facilityName: z.string(),
  currentCount: z.number().int().min(0),
  maxCapacity: z.number().int().min(0),
  lastUpdated: z.string().datetime(),
});
export type FacilityUsageItem = z.infer<typeof FacilityUsageItem>;

// ── Chat ────────────────────────────────────────────────────────────

export const ChatRole = z.enum(["user", "assistant"]);
export type ChatRole = z.infer<typeof ChatRole>;

export const ChatMessage = z.object({
  role: ChatRole,
  content: z.string().max(5000),
  timestamp: z.string().datetime().optional(),
});
export type ChatMessage = z.infer<typeof ChatMessage>;

export const ChatRequest = z.object({
  message: z.string().min(1).max(2000),
  conversationHistory: z.array(ChatMessage).max(50).default([]),
});
export type ChatRequest = z.infer<typeof ChatRequest>;

export const ChatResponse = z.object({
  reply: z.string(),
  disclaimer: z.string().default(
    "I'm an AI fitness assistant. My responses are not medical advice."
  ),
});
export type ChatResponse = z.infer<typeof ChatResponse>;

// ── ICS Import (Phase 2 scaffolding) ────────────────────────────────

export const IcsImportRequest = z.object({
  icsUrl: z.string().url(),
});
export type IcsImportRequest = z.infer<typeof IcsImportRequest>;

export const IcsEvent = z.object({
  summary: z.string(),
  startTime: z.string().datetime(),
  endTime: z.string().datetime(),
  location: z.string().optional(),
  recurrence: z.string().optional(),
});
export type IcsEvent = z.infer<typeof IcsEvent>;

export const IcsImportResponse = z.object({
  events: z.array(IcsEvent),
  warnings: z.array(z.string()).default([]),
});
export type IcsImportResponse = z.infer<typeof IcsImportResponse>;
