import 'package:flutter_test/flutter_test.dart';
import 'package:purdue_personal_trainer/models/schedule_block.dart';
import 'package:purdue_personal_trainer/models/daily_plan.dart';
import 'package:purdue_personal_trainer/models/facility_usage.dart';
import 'package:purdue_personal_trainer/models/chat_message.dart';

void main() {
  group('ScheduleBlock', () {
    test('serializes to/from JSON', () {
      final block = ScheduleBlock(
        id: '123',
        title: 'CS 252',
        dayOfWeek: 'monday',
        startTime: '09:30',
        endTime: '10:20',
        location: 'LWSN B134',
        category: 'class',
      );

      final json = block.toJson();
      final restored = ScheduleBlock.fromJson(json);

      expect(restored.id, '123');
      expect(restored.title, 'CS 252');
      expect(restored.dayOfWeek, 'monday');
      expect(restored.startTime, '09:30');
      expect(restored.endTime, '10:20');
      expect(restored.location, 'LWSN B134');
      expect(restored.category, 'class');
    });
  });

  group('DailyPlan', () {
    test('parses sample plan response', () {
      final json = {
        'id': '2025-01-15',
        'uid': 'abc123',
        'date': '2025-01-15',
        'items': [
          {
            'time': '07:00',
            'duration': 30,
            'activity': 'Morning warm-up and stretching',
            'category': 'wellness',
            'location': 'Home / Dorm',
          },
          {
            'time': '10:30',
            'duration': 60,
            'activity': 'Push/Pull split – moderate intensity',
            'category': 'gym',
            'location': 'CoRec Weight Room',
            'notes': 'Goals: Build muscle, Improve cardio',
          },
        ],
        'generatedAt': '2025-01-15T06:00:00Z',
        'disclaimer': 'This plan is generated by AI and is not medical advice.',
      };

      final plan = DailyPlan.fromJson(json);

      expect(plan.id, '2025-01-15');
      expect(plan.items.length, 2);
      expect(plan.items[0].activity, 'Morning warm-up and stretching');
      expect(plan.items[1].duration, 60);
    });
  });

  group('FacilityUsageItem', () {
    test('calculates usage percent', () {
      final item = FacilityUsageItem(
        facilityName: 'CoRec',
        currentCount: 150,
        maxCapacity: 300,
        lastUpdated: '2025-01-15T10:00:00Z',
      );

      expect(item.usagePercent, 0.5);
    });

    test('handles zero capacity', () {
      final item = FacilityUsageItem(
        facilityName: 'Unknown',
        currentCount: 0,
        maxCapacity: 0,
        lastUpdated: '2025-01-15T10:00:00Z',
      );

      expect(item.usagePercent, 0.0);
    });
  });

  group('ChatMessage', () {
    test('identifies user vs assistant', () {
      final userMsg = ChatMessage(role: 'user', content: 'Hello');
      final assistantMsg = ChatMessage(role: 'assistant', content: 'Hi there');

      expect(userMsg.isUser, true);
      expect(userMsg.isAssistant, false);
      expect(assistantMsg.isUser, false);
      expect(assistantMsg.isAssistant, true);
    });
  });
}
