/// Mirrors the DailyPlan/PlanItem schemas from @ppt/shared.
class PlanItem {
  PlanItem({
    required this.time,
    required this.duration,
    required this.activity,
    required this.category,
    this.location,
    this.notes,
  });

  factory PlanItem.fromJson(Map<String, dynamic> json) {
    return PlanItem(
      time: json['time'] as String,
      duration: json['duration'] as int,
      activity: json['activity'] as String,
      category: json['category'] as String,
      location: json['location'] as String?,
      notes: json['notes'] as String?,
    );
  }

  final String time;
  final int duration;
  final String activity;
  final String category;
  final String? location;
  final String? notes;

  Map<String, dynamic> toJson() {
    return {
      'time': time,
      'duration': duration,
      'activity': activity,
      'category': category,
      'location': location,
      'notes': notes,
    };
  }
}

class DailyPlan {
  DailyPlan({
    required this.id,
    required this.uid,
    required this.date,
    required this.items,
    required this.generatedAt,
    this.disclaimer = 'This plan is generated by AI and is not medical advice. '
        'Consult a healthcare professional before starting any fitness program.',
  });

  factory DailyPlan.fromJson(Map<String, dynamic> json) {
    return DailyPlan(
      id: json['id'] as String,
      uid: json['uid'] as String,
      date: json['date'] as String,
      items: (json['items'] as List<dynamic>)
          .map((e) => PlanItem.fromJson(e as Map<String, dynamic>))
          .toList(),
      generatedAt: json['generatedAt'] as String,
      disclaimer: json['disclaimer'] as String? ??
          'This plan is generated by AI and is not medical advice.',
    );
  }

  final String id;
  final String uid;
  final String date;
  final List<PlanItem> items;
  final String generatedAt;
  final String disclaimer;

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'uid': uid,
      'date': date,
      'items': items.map((e) => e.toJson()).toList(),
      'generatedAt': generatedAt,
      'disclaimer': disclaimer,
    };
  }
}
